function sendLogCafefScroll(d,a){var f=document.getElementById(d);if(null!=f){var k=f.getElementsByTagName("LI"),c=document.URL,g=c.split("/");g=g[0]+"//"+g[2];c=c.replace(g,"");f="undefined"!=f.getAttribute("dmtb")&&null!=f.getAttribute("dmtb")&&""!=f.getAttribute("dmtb")?f.getAttribute("dmtb"):"";if(0<k.length)for(var m=0;m<k.length;m++){var b=k[m],e="undefined"!=b.getAttribute("data-id")&&null!=b.getAttribute("data-id")&&""!=b.getAttribute("data-id")?b.getAttribute("data-id"):"",n=new trackingViewScroll(d,
b,a);b=b.getElementsByTagName("a");for(var l=0;l<b.length;l++){var h=b[l].href;if(-1==h.indexOf("lg1.logging.admicro.vn/nd")){var p="//lg1.logging.admicro.vn/nd?nid="+e+"&zid="+f+"&dmn="+encodeURIComponent(g)+"&cov=1&url="+encodeURIComponent(c)+"&re="+encodeURIComponent(h)+"&covid=0&gid="+ADM_AdsTracking.get("__uid")+"&ext=";b[l].href=p}}e="//lg1.logging.admicro.vn/nd?nid="+e+"&zid="+f+"&dmn="+encodeURIComponent(g)+"&cov=0&url="+encodeURIComponent(c)+"&re="+encodeURIComponent(h)+"&covid=0&gid="+ADM_AdsTracking.get("__uid")+
"&ext=";n.timeLog(e)}}}
function trackingViewScroll(d,a,f){var k=this,c="";this.timeLog=function(a){c=a;this.sTimer=-1;k.scroll_time();document.getElementById("listNewHeader").addEventListener("scroll",function(){k.scroll_time()});window.addEventListener("scroll",k.scroll_time)};this.getScrollTop=function(){var a=document.body.scrollTop;0==a&&(a=window.pageYOffset?window.pageYOffset:document.body.parentElement?document.body.parentElement.scrollTop:0);return a};this.scroll_active_view=function(){var a=!1,c=window.innerHeight,
b=k.getScrollTop()+c,e=document.getElementById(d);if(null!=e){var f=ADS_CHECKER.getElementTop(d),l=f+e.clientHeight/2,h=c/4,p=f+e.clientHeight+h;e=e.clientHeight;0<e&&(a||(0==f?a=!0:0<f&&(e<c?b>l&&b<l+c&&(a=!0):b>f+3*h&&b<p&&(a=!0))))}return a};this.scroll_time=function(){!k.send&&k.scroll_active_view()&&(-1!=k.sTimer&&clearTimeout(k.sTimer),k.sTimer=window.setTimeout(function(){k.scroll_view()},1E3))};this.scroll_view=function(){var g=!1,d=document.getElementById("listNewHeader").scrollTop+f;if(null!=
a){var b=a.offsetTop,e=b+a.clientHeight/2,n=e+f,l=f/4,h=b+a.clientHeight+l,p=a.clientHeight;0<p&&(g||(0==b?g=!0:0<b&&(p<f?d>e&&d<n&&(g=!0):d>b+3*l&&d<h&&(g=!0))));g&&document.images&&""!=c&&((g=c)&&""!=g&&(d=__AdmsendRandom||"",(new Image).src=g+d),k.send=!0)}}}
function sendLogCafef(d){var a=document.getElementById(d);if(null!=a){var f=a.getElementsByTagName("LI"),k="undefined"==a.getAttribute("algid")||null==a.getAttribute("algid")||""==a.getAttribute("algid")?0:a.getAttribute("algid"),c="undefined"==a.getAttribute("boxid")||null==a.getAttribute("boxid")||""==a.getAttribute("boxid")?0:a.getAttribute("boxid"),g="undefined"==a.getAttribute("dspid")||null==a.getAttribute("dspid")||""==a.getAttribute("dspid")?0:a.getAttribute("dspid"),m="undefined"==a.getAttribute("last-id")||
null==a.getAttribute("last-id")||""==a.getAttribute("last-id")?0:a.getAttribute("last-id"),b=document.URL,e=b.split("/"),n=e[0]+"//"+e[2],l=b.replace(n,"");null!=b.match(/[0-9]+rf/g)?(b=b.match(/[0-9]+rf/g),b=b[0].replace("rf","")):(b=b.match(/[0-9]+.chn/g),b=b[0].replace(".chn",""));if("undefined"==window["AdmCount_"+d+"_"+b]||null==window["AdmCount_"+d+"_"+b]||""==window["AdmCount_"+d+"_"+b])window["AdmCount_"+d+"_"+b]=0;a=new trackingViewCafef_v2(a);var h="//lg1.logging.admicro.vn/nd?nid=0&type=1&zid=-1&dmn="+
encodeURIComponent(n)+"&cov=0&url="+encodeURIComponent(l)+"&covid=0&gid="+ADM_AdsTracking.get("__uid")+"&ext="+encodeURIComponent("lastid_"+m+",rc_"+(c+"_"+g+"_"+k))+"&bx="+c+"&dsp="+g+"&alg="+k;a.timeLog(h);if(0<f.length){for(a=window["AdmCount_"+d+"_"+b];a<f.length;a++){h=f[a];var p="undefined"!=h.getAttribute("data-newsid")&&null!=h.getAttribute("data-newsid")&&""!=h.getAttribute("data-newsid")?h.getAttribute("data-newsid"):"";if(""==p){var q=h.querySelector("a");q&&q.href&&((e=/([0-9]+)rf([0-9]+).chn/.exec(q.href+
""))&&2<=e.length?(p=e[1],h.setAttribute("data-newsid",p)):(e=/([0-9]+).chn/.exec(q.href+""))&&2<=e.length&&(p=e[1],h.setAttribute("data-newsid",p)))}e=new trackingViewCafef_v2(h);if(0==h.getAttribute("ispopup")){q=h.getElementsByTagName("a");for(var t=0;t<q.length;t++){var r=q[t].href;-1==r.indexOf("lg1.logging.admicro.vn/nd")&&(r="//lg1.logging.admicro.vn/nd?nid="+p+"&zid=-1&dmn="+encodeURIComponent(n)+"&cov=1&url="+encodeURIComponent(l)+"&re="+r+"&covid=0&gid="+ADM_AdsTracking.get("__uid")+"&ext=lastid_"+
m+"&bx="+c+"&dsp="+g+"&alg="+k,q[t].href=r)}}1==h.getAttribute("ispopup")&&(r="//lg1.logging.admicro.vn/nd?nid="+p+"&zid=-1&dmn="+encodeURIComponent(n)+"&cov=1&url="+encodeURIComponent(l)+"&re=&covid=0&gid="+ADM_AdsTracking.get("__uid")+"&ext=lastid_"+m+"&bx="+c+"&dsp="+g+"&alg="+k,e.logClick(r));h="//lg1.logging.admicro.vn/nd?nid="+p+"&zid=-1&dmn="+encodeURIComponent(n)+"&cov=0&url="+encodeURIComponent(l)+"&covid=0&gid="+ADM_AdsTracking.get("__uid")+"&ext=lastid_"+m+"&bx="+c+"&dsp="+g+"&alg="+k;
e.timeLog(h)}window["AdmCount_"+d+"_"+b]=f.length}}}
function trackingViewCafef_v2(d){var a=this;this.send=!1;var f="",k=function(a){if(a&&""!=a){var c=__AdmsendRandom||"";(new Image).src=a+c}};this.timeLog=function(c){this.sTimer=-1;f=c;checkInPopup?(a.scroll_time(),document.getElementsByClassName("light-box-content")[0].addEventListener("scroll",a.scroll_time)):(a.scroll_time(),window.addEventListener("scroll",a.scroll_time))};this.logClick=function(a){d.addEventListener("click",function(){document.images&&""!=a&&k(a)})};this.scroll_time=function(){a.send||
(-1!=a.sTimer&&clearTimeout(a.sTimer),a.sTimer=window.setTimeout(function(){checkInPopup?a.scroll_view_popup():a.scroll_view()},500))};this.getScrollTop=function(){var a=document.body.scrollTop;0==a&&(a=window.pageYOffset?window.pageYOffset:document.body.parentElement?document.body.parentElement.scrollTop:0);return a};this.getElementTop=function(){if(null!=d){yPos=d.offsetTop;for(tempEl=d.offsetParent;null!=tempEl;)yPos+=tempEl.offsetTop,tempEl=tempEl.offsetParent;return yPos}return 0};this.scroll_view_popup=
function(){var c=!1,g=window.innerHeight,m=document.getElementsByClassName("light-box-content")[0].scrollTop+g;if(null!=d){var b=a.getElementTop(),e=b+d.clientHeight/2,n=g/4,l=b+d.clientHeight+n,h=d.clientHeight;0<h&&(c||(0==b?c=!0:0<b&&(h<g?m>e&&m<e+g&&(c=!0):m>b+3*n&&m<l&&(c=!0))));c&&document.images&&""!=f&&(k(f),a.send=!0)}};this.scroll_view=function(){var c=!1,g=window.innerHeight,m=a.getScrollTop()+g;if(null!=d){var b=a.getElementTop(),e=b+d.clientHeight/2,n=g/4,l=b+d.clientHeight+n,h=d.clientHeight;
0<h&&(c||(0==b?c=!0:0<b&&(h<g?m>e&&m<e+g&&(c=!0):m>b+3*n&&m<l&&(c=!0))));c&&document.images&&""!=f&&(k(f),a.send=!0)}}};